# Generated by Django 3.1.5 on 2021-06-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0005_movies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
    ]
