# Generated by Django 3.1.5 on 2021-06-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0007_auto_20210618_1034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
