# Generated by Django 3.1.5 on 2021-06-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0009_auto_20210618_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies2',
            name='releasedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
