# Generated by Django 3.1.5 on 2021-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0011_auto_20210625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies2',
            name='releasedate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
