# Generated by Django 3.1.5 on 2021-06-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0013_auto_20210625_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies2',
            name='rating',
            field=models.CharField(default=0, max_length=300, null=True),
        ),
    ]
