# Generated by Django 3.1.5 on 2021-06-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0015_auto_20210630_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies2',
            name='releasedate',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
