# Generated by Django 3.1.5 on 2021-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereviews', '0016_auto_20210630_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies2',
            name='releasedate',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
